spring-cloud-config-server-git-uri: https://github.com/lzhcccccch/SpringCloudConfigFile.git
spring-cloud-config-server-git-username: root
spring-cloud-config-server-git-password: root

spring:
  # 配置中心
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: ${spring-cloud-config-server-git-uri}
          # git仓库地址下的相对地址,可以配置多个,用,分割
          search-paths:
          # git仓库的账号
          username: ${spring-cloud-config-server-git-username}
          # git仓库的密码
          password: ${spring-cloud-config-server-git-password}
          timeout: 100